### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by ILysvincent** [ros-drivers/wifi_ddwrt#1]
Hi @ahendrix ,

i am currently trying to figure out how your ros driver works. Is it possible for you to add in a README, so that i ,and perhaps others too, can better understand your work?

Regards,
Vincent

**Comment by trainman419** [comment]
I'll see what I can do about a readme.

In the meantime, wifi_ddwrt is documented on the ROS wiki: http://wiki.ros.org/wifi_ddwrt

**Comment by ILysvincent** [comment]
Thanks a million.
