### ISSUE TITLE
ImportError: No module named pr2 msgs.msg

### ISSUE THREAD

**Issue by ILysvincent** [ros-drivers/wifi_ddwrt#2]
Hi,

I tried running the ddwrt.py node after catkin_make the package. However I keep getting  
"Traceback (most recent call last):
  File "/home/mig-ly/catkin_ws/src/wifi_ddwrt-hydro-devel/nodes/ddwrt.py", line 41, in <module>
    from pr2_msgs.msg import AccessPoint
ImportError: No module named pr2_msgs.msg".

 I have tried running the analysis, ddwrt_sim.py,  and monitor node as well and the same error popped up. I am at the end of my wits. Help will be greatly appreciated.

**Comment by Kurt1812** [comment]
I have the same problem. Any help would be immensely appreciated....

**Comment by trainman419** [comment]
Have you tried installing the pr2_msgs package?

**Comment by Kurt1812** [comment]
what would be the source command?

**Comment by trainman419** [comment]
The `source` command is not an appropriate solution to this problem.

Per the ROS support guidelines, please ask this on http://answers.ros.org
